### ISSUE TITLE
To match a pattern in multiple domain 

### ISSUE THREAD

**Issue by wanghaisheng** [fffonion/lua-resty-acme#1]
how to set "domain_whitelist = { "domain1.com", "domain2.com", "domain3.com" },"

domain_whitelist = setmetatable({}, { __index = function(_, k)
    return ngx.re.match(k, [[\.example\.domain1$] | [\.domain2\.com$]], "jo")
end}),

@fffonion

**Comment by fffonion** [comment]
Hi @wanghaisheng if you just want to match domain1.com, domain2.com and domain3.com, use
```lua
domain_whitelist = { "domain1.com", "domain2.com", "domain3.com" }
```

If you want to match multiple subdomains, you will need to craft a regex pattern that matches both subdomains:
```lua
domain_whitelist = setmetatable({}, { __index = function(_, k)
return ngx.re.match(k, [[(.domain1 com|.domain2.com)$]], "jo")
end}),
```
