### ISSUE TITLE
should expose get_certkey method

### ISSUE THREAD

**Issue by yxy** [fffonion/lua-resty-acme#10]
first of all, awesome job. thanks for your kind work 👍 .

I need to check domain certkey exists or not, but I found this method only private.
It would be very convenient if this method can be exposed. 

```lua
local autossl = require("resty.acme.autossl")
local certkey, err = autossl.get_certkey({domain=ngx.var.server_name, type="rsa"}) 
if certkey and scheme == http then
    ngx.redirect(new_uri, 301)
end

-- I had to hack autoss.lua to make this work

-- make get_certkey visible
AUTOSSL.get_certkey = get_certkey 
```

**Comment by fffonion** [comment]
This has been implemented and will be included in next release : )

**Comment by fffonion** [comment]
@yxy the exposed function is slightly different from internal version, please refer to doc https://github.com/fffonion/lua-resty-acme#autosslget_certkey
