### ISSUE TITLE
dns-01 challenge

### ISSUE THREAD

**Issue by yuweizzz** [fffonion/lua-resty-acme#111]
对于泛解析证书来说， dns-01 是唯一的验证方式，是出于什么原因没有支持吗？

**Comment by fffonion** [comment]
当前的部署模式不适合使用dns-01的验证方式。
而且dns 提供商 API不统一，支持难度大。

**Comment by yuweizzz** [comment]
目前我们已经尝试自行实现 dns-01 验证方式，会在我们的测试环境运行一段时间，如果这个功能成熟的话，您是否会考虑将这个功能合并到主线分支？

**Comment by fffonion** [comment]
@yuweizzz 欢迎提交PR！
