### ISSUE TITLE
etcd storage backend

### ISSUE THREAD

**Issue by fffonion** [fffonion/lua-resty-acme#12]
This is the tracking issue for development.

**Comment by fffonion** [comment]
@chewi I remember you mention a development of etcd backend is on going. I'd like to check if it's being worked on so I can avoid step upon existing works?

**Comment by chewi** [comment]
Sorry, it dropped down the priority list. I believe I had it more or less working, the only remaining issues were related to strictness around Pebble. I'll push what I have anyway as soon as I can.

**Comment by fffonion** [comment]
@chewi Roger, thanks!
