### ISSUE TITLE
Renew failed

### ISSUE THREAD

**Issue by constantineav** [fffonion/lua-resty-acme#14]
Hello! 
I am getting a certificate renewal error. I cannot understand what is the matter.
Thank you in advance.

`
2020/11/11 12:05:33 [error] 12#12: *47966 lua ssl certificate verify error: (20: unable to get local issuer certificate), context: ngx.timer

2020/11/11 12:05:33 [error] 12#12: *47966 [lua] autossl.lua:196: update_cert(): error during acme init: acme directory request failed: 20: unable to get local issuer certificate, context: ngx.timer

2020/11/11 12:05:34 [error] 12#12: *47966 lua ssl certificate verify error: (20: unable to get local issuer certificate), context: ngx.timer

2020/11/11 12:05:34 [error] 12#12: *47966 [lua] autossl.lua:196: update_cert(): error during acme init: acme directory request failed: 20: unable to get local issuer certificate, context: ngx.timer

`

**Comment by fffonion** [comment]
Hi, you will need to configure trusted CA:
```
        # required to verify Let's Encrypt API
        lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        lua_ssl_verify_depth 2;
```

the path is dependent on your OS.

**Comment by constantineav** [comment]
Hi. 
These settings are written initially.


`lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
lua_ssl_verify_depth 2;

ssl_certificate /etc/openresty/default.pem;
ssl_certificate_key /etc/openresty/default.key;

ssl_certificate_by_lua_block {
    require("resty.acme.autossl").ssl_certificate()
}

location /.well-known {
    content_by_lua_block {
        require("resty.acme.autossl").serve_http_challenge()
    }
}


/ # ls -l /etc/ssl/certs/ca-certificates.crt
-rw-r--r--    1 root     root        231411 Sep  9 13:48 /etc/ssl/certs/ca-certificates.crt
/ # 

`

**Comment by fffonion** [comment]
Ah I see, we will need that two lua_ssl_* directives in `http{}` block. Since the renewal timer is started in init_worker phase. I'll update the readme. Thanks for spotting this!

**Comment by fffonion** [comment]
I just updated the readme, feel free to re-open if issue persists.

**Comment by constantineav** [comment]
I see a very strange situation. To exclude any cache in the middle, I make requests locally. But I get different certificates. Here's an example. Requests with a difference of several seconds. The domain is just changed.

```
root@dev:~# curl -v --resolve somesite:443:127.0.0.1 https://somesite > /dev/stdout 2>&1| grep expire
*        expire date: Tue, 17 Nov 2020 09:27:03 GMT
root@dev:~# curl -v --resolve somesite:443:127.0.0.1 https://somesite > /dev/stdout 2>&1| grep expire
*        expire date: Tue, 09 Feb 2021 15:33:24 GMT
root@dev:~# curl -v --resolve somesite:443:127.0.0.1 https://somesite > /dev/stdout 2>&1| grep expire
*        expire date: Tue, 17 Nov 2020 09:27:03 GMT
root@dev:~# curl -v --resolve somesite:443:127.0.0.1 https://somesite > /dev/stdout 2>&1| grep expire
*        expire date: Tue, 17 Nov 2020 09:27:03 GMT
root@dev:~# curl -v --resolve somesite:443:127.0.0.1 https://somesite > /dev/stdout 2>&1| grep expire
*        expire date: Tue, 17 Nov 2020 09:27:03 GMT
root@dev:~# curl -v --resolve somesite:443:127.0.0.1 https://somesite > /dev/stdout 2>&1| grep expire
*        expire date: Tue, 09 Feb 2021 15:33:24 GMT
```

**Comment by fffonion** [comment]
@constantineav There's a cache of 1 hr, we don't actively invalidate cache right now. This can be improvement.

**Comment by wangyp0701** [comment]
Can I renew the certificate automatically after it has expired ? @fffonion

**Comment by fffonion** [comment]
@wangyp0701 yes

**Comment by fffonion** [comment]
@wangyp0701 Which version of library are you using? Let's also open a new issue instead of discussing in a closed one.

**Comment by wangyp0701** [comment]
All expired certificates are updated at zero

![image](https://user-images.githubusercontent.com/33682005/99329269-cfc7bf80-28b8-11eb-833c-b6183e8cab58.png)
