### ISSUE TITLE
whitelist not working

### ISSUE THREAD

**Issue by tohodakilla** [fffonion/lua-resty-acme#18]
I have configured package according to the docs and yet any domain i point to this server gets a certificate

```
    resolver 127.0.0.53 ipv6=off;

    init_by_lua_block {
        require("resty.acme.autossl").init({
            tos_accepted = true,
            enabled_challenge_handlers = { 'http-01', 'tls-alpn-01' },
            account_key_path = "/etc/openresty/account.key",
            account_email = "shuib@pm.me",
            domain_whitelist = { "kust.domain.tld", "another.tld", "domain.tld" },
        })
    }

    init_worker_by_lua_block {
        require("resty.acme.autossl").init_worker()
    }

    include       mime.types;
    default_type  application/application-json;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;

    keepalive_timeout   65;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

    access_log /var/log/openresty/access.log;
    error_log /var/log/openresty/error.log;

    gzip on;

server {
    listen 80;
    listen 443 ssl;
    server_name _;

    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
    lua_ssl_verify_depth 2;

    ssl_certificate /etc/letsencrypt/live/domain.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain.tld/privkey.pem;

    ssl_certificate_by_lua_block {
        require("resty.acme.autossl").ssl_certificate()
    }

    location /.well-known {
        content_by_lua_block {
            require("resty.acme.autossl").serve_http_challenge()
        }
    }
    location / {
        proxy_pass http://10.110.0.2:3000;
    }
}

}
```
openresty v: 1.19.3.1 with opm

When I point diffferent.tld or sub.domain.tld to gateway it still gets certificate, besides not being in the whitelist.
what I might be doing wrong?

**Comment by fffonion** [comment]
@tohodakilla could you set the top level `error_log /var/log/openresty/error.log;` to `error_log /var/log/openresty/error.log debug;` and share the log lines containing the domain name `diffferent.tld` or `sub.domain.tld`?

**Comment by tohodakilla** [comment]
i have cleared the log and added one you requested:

_**here is for what is show in the log for sub.domain.tld:**_
2020/11/25 17:49:00 [info] 20337#0: [lua] openssl.lua:5: using ffi, OpenSSL version linked: 1010106f
2020/11/25 17:49:00 [error] 20337#0: init_by_lua error: /usr/local/openresty/site/lualib/resty/acme/autossl.lua:434: can't open account_key file /etc/openresty/account.key: /etc/openresty/account.key: No such f>
stack traceback:
        [C]: in function 'error'
        /usr/local/openresty/site/lualib/resty/acme/autossl.lua:434: in function 'load_account_key'
        /usr/local/openresty/site/lualib/resty/acme/autossl.lua:283: in function 'init'
        init_by_lua:2: in main chunk

**Comment by tohodakilla** [comment]
I have recreated entire setup from scratch on new box and it works as it should.

**Comment by fffonion** [comment]
@tohodakilla I assume you are all good on the issue here then. If so feel free to close the ticket : )
