### ISSUE TITLE
Consistent CI Tests

### ISSUE THREAD

**Issue by cdloh** [fffonion/lua-resty-acme#28]
At present the Unit tests are a bit haphazard. Based off reading the latest logs quite a few of the problems appear to be around frp.

I had a few options on what could be done to make this more consistent / easier for people to join.

1. Move to ngrok

Positives?

  * Most of the other autossl  / LetEncrypt projects use this so makes it easier for people to move across projects (unlikely but handy?)
  * Users only have to set ngrok secrets on their forks rather then having to host a frp endpoint themselves.
  
Negatives
  * Only one test matrix can run at a time due to limitations on the free ngrok usage
  * Only one subdomain available for testing
  * Still requires people to create accounts 

2. Use a local ACME instance eg [pebble](https://github.com/letsencrypt/pebble) as a service within the actions

Positives
  * Full control within the actions
  * No setup required from people using forks
  * Can do multiple domains using netalias within the docker network

Negatives
  * APIs can potentially be out of sync with main LE APIs

Maybe it would be best to do a combination of both.

Pebble sidecar runs on forks so no setup is required on people doing work for forks etc before creating MRs.
MRs run against the staging LE server using either frp or ngrok

Would like your thoughts on this and if you want to look at going down either of these paths @fffonion !

**Comment by UXabre** [comment]
I also noticed the ci test issues and had a hard time getting something to work, in the end i singled out my test and at least I can sleep...
I'm new on the acme service side of life, but from your proposals I think pebble looks promising.
Perhaps a "smoke test" hybrid can be made in which ngrok is simply used to verify compatibility and all other tests could use pebble?
Just my 2 cents :-)

**Comment by fffonion** [comment]
I agree moving to use pebble is the right way to go. I intially choose `frp` to avoid a lock-in with `ngrok`,
which doesn't have a clear status of how long its free services will last.

But on the other hand either ngrok or frp should not make the test itself flakky, so the failing tests *may*  indicates
some bugs in code, but I haven't been able to figure out yet.

**Comment by fffonion** [comment]
Closing this as tests have been moved to pebble.
