### ISSUE TITLE
can't get new nonce from acme server

### ISSUE THREAD

**Issue by Laboltus** [fffonion/lua-resty-acme#39]
Since some time, my certificates have stopped updating. I error log I see such error for all my domains:
`[lua] autossl.lua:174: update_cert_handler(): error updating cert for domain.com err: failed to create new order: can't get new nonce from acme server, context: ngx.timer`
I tried to get nonce by hand and it works:
```
# curl -k -I https://acme-v02.api.letsencrypt.org/acme/new-nonce
HTTP/2 200 
server: nginx
date: Wed, 12 May 2021 08:21:14 GMT
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 0103MSkULKV6LUWKI59T_afSuNeQRtcuI5Wp6NEtPRgZ-Bs
x-frame-options: DENY
strict-transport-security: max-age=604800
```
Also I found that from Jan 17 response code for HEAD request changed from 204 to 200 but as I see in client.lua you don't check the response code.

**Comment by fffonion** [comment]
That looks more like a network issue to me, as we only error out in `new_nonce` when HTTP connection is broken
(https://github.com/fffonion/lua-resty-acme/blob/a1782c994209450fc41deca8bf970d005fd17126/lib/resty/acme/client.lua#L368). I can popup the error in `jws`
so it's more visible.

**Comment by fffonion** [comment]
The error popup is done in https://github.com/fffonion/lua-resty-acme/commit/a19e9c8af9179a81815c653d176aa0bfc27e532b, closing as it seems not an issue from this library.
Please feel free to reopen if you see this situation again.

**Comment by Laboltus** [comment]
I changed the storage from consul to redis and it works at the time. I will let you know if it happens again.
