### ISSUE TITLE
Differences from lua-resty-auto-ssl?

### ISSUE THREAD

**Issue by kajmagnus** [fffonion/lua-resty-acme#5]
Hi Wangchong @fffonion

Nice with automatic https for Nginx / OpenResty :- ) 

Can I ask, 1) what are the differences between this project, *lua-resty-acme* and  https://github.com/auto-ssl/lua-resty-auto-ssl ? And 2) what are the reasons this is a different project than lua-resty-auto-ssl (instead of building on lua-resty-auto-ssl)?

Some differences I noticed: This project can be installed using opm (OpenResty Package Manager), and supports more storages: Valut and Consul too. And this project supports tls-alpn-01 — maybe *lua-resty-auto-ssl* doesn't? (didn't see -alpn- mentioned in that project)

**Comment by fffonion** [comment]
Hi @kajmagnus, the initial purpose of this library is to support [kong/kong-plugin-acme](https://github.com/Kong/kong-plugin-acme). And we don't want to depend on a third party program (`dehydrated`) as lua-resty-auto-ssl does. So I create this library and the [supporting openssl library](https://github.com/fffonion/lua-resty-openssl) which reduces complexity for deployment. And dependency free means it's possible to install from OPM.

I believe you can use tls-alpn-01 for `dehydrated` but i didn't test for lua-resty-auto-ssl. Also do notice that the support of tls-alpn-01 in this library is experimental : )

**Comment by kajmagnus** [comment]
Ok thanks for the reply and info  :- )

Yes, just a little bit later I noticed you're also developing https://github.com/Kong/kong-plugin-acme. Kong looks nice I think — I'm currently using Nginx, about to switch to OpenResty, maybe Kong some day in the future
