### ISSUE TITLE
How do I use ZeroSSL?

### ISSUE THREAD

**Issue by nahin-web** [fffonion/lua-resty-acme#62]
Do I have to call the zeroSSL lua file in the `eab_handler` config?

**Comment by fffonion** [comment]
@nahin-web No you only need set the correct `api_uri`.

**Comment by nahin-web** [comment]
Didn't work. I used `https://acme.zerossl.com/v2/DV90` 
I was considering ZeroSSL, as I stuck into Let's Encrypt's rate limiting. Despite having ZeroSSL `api_url`, I get the same rate limit reached error message on the error log

`init_by_lua_block {
            require("resty.acme.autossl").init({
                -- setting the following to true
                -- implies that you read and accepted https://letsencrypt.org/repository/
                tos_accepted = true,
                -- uncomment following for first time setup
                -- staging = true,
                -- uncomment following to enable RSA + ECC double cert
                domain_key_types = { 'rsa', 'ecc' },
                -- uncomment following to enable tls-alpn-01 challenge
                -- enabled_challenge_handlers = { 'http-01', 'tls-alpn-01' },
                account_key_path = "/etc/openresty/account.key",
                account_email = "email@example.com",
                domain_whitelist = { "mysite.us.to" },
                api_url = "https://acme.zerossl.com/v2/DV90"
        })
      }`

**Comment by fffonion** [comment]
`api_uri` is the config for underlying client, so you should do
```lua
require("resty.acme.autossl").init({
  -- you current configs
},
{
  api_url = "https://acme.zerossl.com/v2/DV90" 
})
```
