### ISSUE TITLE
Error while trying to use subdomain with "_" simbol

### ISSUE THREAD

**Issue by n3on4s** [fffonion/lua-resty-acme#64]
Hi,

I'm not sure where the problem is but when trying to whitelist and issue certificate for subdomain with underscore symbol `_` issuing fails with the fallowing error:

```
[error] 23251#23251: *2978 [acme] autossl.lua:189: error updating cert for smart_panel.example.com err: failed to create new order: Error creating new order :: Cannot issue for "smart_panel.example.com ": Domain name contains an invalid character, context: ngx.timer, client ...
```

end whenever I drop _ symbol everything works as expected.

**Comment by stardothosting** [comment]
Underscore characters are not permitted in domain names in accordance with RFC 1035, which only allows letters, digits and hyphens. If you cannot register a domain with an underscore than I wouldn't expect it to work here?

**Comment by fffonion** [comment]
@n3on4s Right as @stardothosting suggested, those are non permitted characters and the error is thrown from the ACME service. There's little we can do on the client side; i'm closing this one, please re-open if you have other questions : )
