### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Hackintoshcorp** [fffonion/lua-resty-acme#67]
Hi so I installed

luarocks install lua-resty-acme
luarocks install luafilesystem

also did everything here https://github.com/fffonion/lua-resty-acme#synopsis

but still don't get the certificate when I go to my website.

How do you use it? 😄 

Do I need to run a command to get a SSL? I want to get SSL from zerossl.com because let's encrypt does not work.

My config:

```
events {}

http {
    resolver 8.8.8.8;

    lua_shared_dict acme 16m;

    # required to verify Let's Encrypt API
    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
    lua_ssl_verify_depth 2;
 
		init_by_lua_block {
		require("resty.acme.autossl").init({
		  -- you current configs
		tos_accepted = true,
		        account_key_path = "/etc/openresty/account.key",
		        account_email = "email@gmail.com",

		  eab_kid = "130jnnbfmhTA2-kCDWe5FAg",
		  -- external account binding hmac key, base64url encoded
		  eab_hmac_key = "15BVuaSD82WD2q3C5Q-l1Xn8X9L6m9i5jhlPMx3LTooiXr4xBoBwnD9mzf16JKdyzxrKKHGFaI6kZU5eE7hPcJA",
		        --domain_whitelist = { " yyy.com" }
		},
		{
		  api_url = "https://acme.zerossl.com/v2/DV90" 
		})}

   init_worker_by_lua_block {
        require("resty.acme.autossl").init_worker()
    }

    server {
        listen 80;
        listen 443 ssl;
        server_name yyy.com;
				location = /.well-known {
            content_by_lua_block {
                require("resty.acme.autossl").serve_http_challenge()
            }
        }
        # fallback certs, make sure to create them before hand
        ssl_certificate /etc/openresty/default.pem;
        ssl_certificate_key /etc/openresty/default.key;

        ssl_certificate_by_lua_block {
            require("resty.acme.autossl").ssl_certificate()
        }
    }


}
```

**Comment by fffonion** [comment]
Hi @Hackintoshcorp you might want to check the Nginx error log, it should give you some diagnostic information.

**Comment by Hackintoshcorp** [comment]
> Hi @Hackintoshcorp you might want to check the Nginx error log, it should give you some diagnostic information.

My question is does this LUA script make SSL automatically just like https://github.com/auto-ssl/lua-resty-auto-ssl ? And can ZeroSSL be used with this? What config should be done?

**Comment by fffonion** [comment]
Yes it does automagic stuff, but unlike resty-auto-ssl, when first request on an SNI it doesn't block the request. The process runs in background.
And it does support ZeroSSL, your config looks correct to me at first glance.

**Comment by Hackintoshcorp** [comment]
@fffonion 
I get this error from the log. Have any idea on how to fix it? Fresh install of Openresty 1.21.4-1 btw

2022/07/10 10:25:02 [error] 120523#0: *14 open() "/etc/nginx/nginx/html/.well-known/acme-challenge/t9xG-IzklLS0sSZzng9g0mkxzyB3D-r46JDxEWvEg00" failed (2: No such file or directory), client: IP1.2.2.2, server: ccc.lt, request: "GET /.well-known/acme-challenge/t9xG-IzklLS0sSZzng9g0mkxzyB3D-r46JDxEWvEg00 HTTP/1.1", host: "ccc.lt"

2022/07/10 10:25:03 [error] 120523#0: *15 open() "/etc/nginx/nginx/html/.well-known/acme-challenge/t9xG-IzklLS0sSZzng9g0mkxzyB3D-r46JDxEWvEg00" failed (2: No such file or directory), client: IP1.2.2.2, server: ccc.lt, request: "GET /.well-known/acme-challenge/t9xG-IzklLS0sSZzng9g0mkxzyB3D-r46JDxEWvEg00 HTTP/1.1", host: "ccc.lt"

2022/07/10 10:25:03 [error] 120523#0: *16 open() "/etc/nginx/nginx/html/.well-known/acme-challenge/t9xG-IzklLS0sSZzng9g0mkxzyB3D-r46JDxEWvEg00" failed (2: No such file or directory), client: IP1.2.2.2, server: ccc.lt, request: "GET /.well-known/acme-challenge/t9xG-IzklLS0sSZzng9g0mkxzyB3D-r46JDxEWvEg00 HTTP/1.1", host: "ccc.lt"

2022/07/10 10:25:04 [error] 120523#0: *4 [acme] autossl.lua:189: error updating cert for ccc.lt err: error checking challenge: challenge invalid: http-01: invalid: IP1.2.2.2: Invalid response from http://ccc.lt/.well-known/acme-challenge/t9xG-IzklLS0sSZzng9g0mkxzyB3D-r46JDxEWvEg00: 404, context: ngx.timer, client: IP1.2.2.2, server: 0.0.0.0:443

**Comment by Hackintoshcorp** [comment]
@fffonion the location should be /.well-known/acme-challenge/ not location = /.well-known{

**Comment by Hackintoshcorp** [comment]
2022/07/10 14:26:54 [debug] 121323#0: *9 [acme] client.lua:307: acme request: https://acme-v02.api.letsencrypt.org/acme/new-acct response: {
  "key": {
    "kty": "RSA",
    "n": "zzJEM8bqlEpOigYq0BkerTS1UACVwIgfU_q0zIAsCkyjyiiCYyo1IvOZDWw3v_XiMTc0DyXLudvEhYzOz6AUf7KPTeH6KEsArzf0AUdwyLvZ_Wz9OlW66KCZ1ljxrkmOpH81rc2sQeXgLmm0SShTqDCOcC7lPpHxsiwHZTHmqJ2lHfAPwEBEHogzZBsNNu53ygotChL8ZoNNQUe9lxABLsp6jNCY3_cFEWx0_MsL>
    "e": "AQAB"
  },
  "contact": [
    "mailto:email@gmail.com"
  ],
  "initialIp": "2a02:4780:9:0:2:bc53:9a62:fd8a",
  "createdAt": "2022-07-10T14:18:00Z",
  "status": "valid"
}

@fffonion  the request is still being transferred to let's encrypt instead of zero ssl. Could you help me with the config? or am I missing something because lets encrypt has rate-limits thats why I want to use zero ssl acme not lets encrypt acme.
