### ISSUE TITLE
Account key and domain keys written as files regardless of storage backend?

### ISSUE THREAD

**Issue by chewi** [fffonion/lua-resty-acme#7]
Is this deliberate? It seems like an odd mismatch to me. My nginx is a Kubernetes pod so the local storage may disappear. My etcd storage, however, is persistent. And yes, my colleague is writing an etcd backend for this project. :smile:

Perhaps you can convince me why files are more appropriate here. Otherwise would you accept a patch to change this behaviour? Or perhaps make it configurable?

While I'm here, I'm changing `api_uri` to point to my test ACME server but it's still trying to use the real one. Haven't figured out why yet.

We're working on this as a company hackathon project over the next day so a speedy response would be appreciated.

**Comment by fffonion** [comment]
Hi @chewi , account key is currently read ad file if defined, or generate on the fly when autossl initializes. Patches are definitely welcomed to load account key from storage backend. You will want to do that in AUTOSSL.init_worker while cosocket api is available. 

Domain keys however are always stored together with certificates in storage. (You can use domain_keys_path to desiginite one but that's mainly used for testing, in production you will want omit that and generate different keys per domain on the fly).

Could you share with me an example on how you are using api_uri and it's not effective?

**Comment by chewi** [comment]
Thanks for your quick reply!

I figured out the problem. I hadn't noticed that `autossl.init` takes two tables and `api_uri` needs to go in the second one. Other settings like `account_email` are copied over so this is a bit confusing.

Unfortunately I didn't get my project working in time but I was close so maybe I'll continue it. Some problems stemmed from testing with [Pebble](https://github.com/letsencrypt/pebble) and I'll be filing a couple of pull requests to address those. I'll keep this issue open until it is resolved.

**Comment by fffonion** [comment]
This is already implemented in #16
