### ISSUE TITLE
Problem with update locks

### ISSUE THREAD

**Issue by kozak** [fffonion/lua-resty-acme#81]
Hi, 
we are occasionally seeing a problem with an `update_lock` not being released, which causes certificates not to be renewed until the lock is manually cleared. 

```
2022/02/14 14:38:02 [info] 16#16: *37134811 [lua] autossl.lua:250: update_cert(): update is already running (lock key update_lock::www.somedomain.com exists), current type rsa, context: ngx.timer
```

Any idea what could lead to this? 

Thank you very much!

**Comment by fffonion** [comment]
The update_lock by default expires 300s, unless a cert is sucessfully issued. You might need to check the error log above this line, it could be a misconfiguration, or a bug in code.

**Comment by fffonion** [comment]
Closing for inactively, please reopen if needed.

**Comment by kozak** [comment]
We've noticed that the keys don't have the TTL set, meaning that `pexpire` didn't succeed. 
A switch to atomic `set` is in the PR.

**Comment by kozak** [comment]
@fffonion can we please re-open this? Also, if you will find time, could you please review the PR that fixes it :)  ?
