### ISSUE TITLE
Option to delete none whitelisted domains in certificate update

### ISSUE THREAD

**Issue by joergmoldenhauer** [fffonion/lua-resty-acme#85]
In our usage of this library a domain which is in the whitelist might be removed from the whitelist later. We would appreciate it if the domain is then removed from the storage used by this library, too. This could be done in the certificate upate process.

In `AUTOSSL.update_cert` an error message is returned when a domain is not whitelisted. It would be nice to have an option that instead of returning an error message the domain is deleted from storage. That way a none whitlisted domain would not have to be checked every time the worker is running and there would not be unnecessary messages in the log.

**Comment by fffonion** [comment]
@joergmoldenhauer That's a good idea. PRs are welcome! I will pick it up if no one is working on it : )

**Comment by DoobleD** [comment]
We're very much interested in that feature as well. :)
